
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE map (
  cordx INTEGER NOT NULL,
  cordy INTEGER NOT NULL,
  color TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  author_id INTEGER NOT NULL,
  PRIMARY KEY (cordx, cordy),
  FOREIGN KEY (author_id) REFERENCES user (id)
);
